### ISSUE TITLE
[fix] 이미지 요청이 몰릴 시 500 error

### ISSUE THREAD

**Issue by rvbear** [TUK-DP/backend#153]
### 오류 내용
에러로그 함께 입력  
<br>

**Comment by Leewonchan14** [comment]
open AI 이미지 요청이 문제가 아닌 이미지 업로드 문제인거 같아요

현재 로직상 클라이언트에서 각 5개 키워드 그림을 하나씩 s3에 업로드 하고 그림저장시 업로드된 5개의 그림을 한번에 저장을 하는 방식입니다.

각 키워드 마다 그림 저장(캡쳐) 하는 것으로 변경하고 그림 저장시 한번에 그림 저장하는게 아닌 각 키워드 그림이 끝날때마다 그림을 저장하는 방식으로 바꾸는것을 목표로 하는게 어떤가 합니다.

**Comment by Leewonchan14** [comment]
s3 연동하는 부분 try catch 로 묶어서 500에러 방지
